const doctorStamp = [
  'data:image/svg+xml;base64,',
  'PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMDAgMzAw',
  'IiB3aWR0aD0iMzAwIiBoZWlnaHQ9IjMwMCI+CiAgPGltYWdlIHdpZHRoPSIzMDAiIGhlaWdodD0iMzAw',
  'IiBocmVmPSJkYXRhOmltYWdlL2pwZWc7YmFzZTY0LC85ai80QUFRU2taSlJnQUJBUUVBQVFBQkFBRC8y',
  'd0JEQUFLRE9NZ0R5d0FEZ3pNERV4QVRFeFlWRXhVVkV4Z1ZGUmdXSWg4aUppQWRIeDRrS0M4cUpDQXZL',
  'Q0FlSlRFd01URTFOREUxSnlvNFBUVTFOVEV4TkRVMU5EVTFOWFgvMndCREFSVVJFUkVRRVJFVkZCRTFKU',
  '0FoTlRVMU5UVTFOUFUxTlRVMU5UVTFOUFUxTlRVMU5UVTFOUFUxTlRVMU5UVTFOUFUxTlRVMU5UVTFOUF',
  'UxTlRVMU5UVTFOUFgvd0FBUkNBRUFBUEFEQVNJQUFoRUJBeEVC处于/9k=iM0ZoooiM0ZoooiM0Zoooi',
  'M0ZoooiM0ZoooiM0ZoooiM0ZoooiM0ZoooiM0ZoooiM0ZoooiM0ZoooiM0ZoooixRRRRF//Z"/>\n</svg>\n'
].join('');
export default doctorStamp;
